print ("⠀⠀     ⠀⠀ ＿＿")
print("        ／＞　　フ")
print("        | 　_　 _ ")
print("       ／` ミ＿xノ")
print("      /　　　 　 |")
print("     /　 ヽ　　 ﾉ")
print("    │　　|　|　|")
print("／￣|　　 |　|　|")
print("| (￣ヽ＿ヽ)__)")
print("＼二つ")
